# This is a Gradle version catalog. It defines dependency versions that are shared across all subprojects.
# For more info, see:
# - https://developer.bluedragonmc.com/development/gradle-setup/#version-catalogs
# - https://docs.gradle.org/current/userguide/platforms.html

[versions]
server = "2026-09-14-e394984"
minestom = "2026.08.16-26.2"
minimessage = "4.24.0"

[libraries]
server = { group = "com.bluedragonmc.server", name="common", version.ref = "server" }
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "minimessage" }
